const productsData = [
  {
    id: 1,
    name: "AI Writing Pro",
    description: "Generate high-quality content using advanced AI tools.",
    price: 29,
    period: "monthly",
    tag: "Best Seller",
    tagType: "best",
    features: ["Unlimited generations", "50+ templates", "Grammar checker"],
    icon: "📝",
  },
  {
    id: 2,
    name: "Design Templates Pack",
    description: "2000+ templates for social media and presentations.",
    price: 49,
    period: "one-time",
    tag: "Popular",
    tagType: "popular",
    features: ["2000+ templates", "Monthly updates", "Commercial license"],
    icon: "🎨",
  },
  {
    id: 3,
    name: "Premium Stock Assets",
    description: "Access millions of royalty-free assets.",
    price: 19,
    period: "monthly",
    tag: "New",
    tagType: "new",
    features: ["10M+ assets", "Commercial use", "No attribution"],
    icon: "📸",
  },
  {
    id: 4,
    name: "Automation Toolkit",
    description: "Automate repetitive tasks efficiently.",
    price: 79,
    period: "monthly",
    tag: "Popular",
    tagType: "popular",
    features: ["50+ automations", "API access", "Custom workflows"],
    icon: "⚙️",
  },
  {
    id: 5,
    name: "Resume Builder Pro",
    description: "Create professional resumes easily.",
    price: 15,
    period: "one-time",
    tag: "New",
    tagType: "new",
    features: ["100+ templates", "ATS optimization", "Export to PDF"],
    icon: "📄",
  },
  {
    id: 6,
    name: "Social Media Content Kit",
    description: "Complete toolkit for content creators.",
    price: 39,
    period: "monthly",
    tag: "Best Seller",
    tagType: "best",
    features: ["500+ assets", "Scheduler tools", "Analytics dashboard"],
    icon: "📱",
  },
];

export default productsData;